package com.example.findmyip.model

/*
data class IpItem(
        val ip: String,
        val network: String,
        val version: String,
        val city: String,
        val region: String,
        val region_code: String,
        val country: String,
        val country_name: String,
        val country_code: String,
        val country_code_iso3: String,
        val country_capital: String,
        val country_tld: String,
        val continent_code: String,
        val in_eu: String,
        val postal: String,
        val latitude: String,
        val longitude: String,
        val timezone: String,
        val utc_offset: String,
        val country_calling_code: String,
        val currency: String,
        val currency_name: String,
        val languages: String,
        val country_area: String,
        val country_population: String,
        val asn: String,
        val org: String,
)

fun FindMyIpModel.toIpItem() = IpItem(
        ip,
        network,
        version,
        city,
        region,
        region_code,
        country,
        country_name,
        country_code,
        country_code_iso3,
        country_capital,
        country_tld,
        continent_code,
        in_eu,
        postal,
        latitude,
        longitude,
        timezone,
        utc_offset,
        country_calling_code,
        currency,
        currency_name,
        languages,
        country_area,
        country_population,
        asn,
        org,
)*/
